#!/usr/bin/env python3
"""
Minecraft Paper Server Launcher for Railway
"""

import os
import sys
import subprocess
import time
import signal
import shutil
import json
import urllib.request
import urllib.error
from pathlib import Path
from typing import Optional, Tuple

# Configuration
MINECRAFT_VERSION = "26.2"
PAPER_BUILD = "112"
JAR_NAME = f"paper-{MINECRAFT_VERSION}-{PAPER_BUILD}.jar"
SERVER_DIR = os.environ.get("SERVER_DIR", "/data/server")
PORT = os.environ.get("PORT", "25565")
OFFLINE_MODE = os.environ.get("OFFLINE_MODE", "false").lower() == "true"

# Logging functions
def log_info(msg: str) -> None:
    print(f"info = [SERVER] - {msg}", flush=True)

def log_warning(msg: str) -> None:
    print(f"warning = [!] - {msg}", flush=True)

def log_error(msg: str) -> None:
    print(f"error = [Err] - {msg}", flush=True)

def log_paper(line: str) -> None:
    line_lower = line.lower()
    if "error" in line_lower or "exception" in line_lower or "failed" in line_lower:
        print(f"error = [PAPER] - {line}", flush=True)
    elif "warn" in line_lower:
        print(f"warning = [!] - {line}", flush=True)
    else:
        print(f"info = [PAPER] - {line}", flush=True)

# Signal handling
server_process = None

def signal_handler(sig, frame):
    log_info("Received SIGTERM, shutting down Minecraft server...")
    if server_process:
        server_process.terminate()
        try:
            server_process.wait(timeout=30)
        except subprocess.TimeoutExpired:
            server_process.kill()
    sys.exit(0)

signal.signal(signal.SIGTERM, signal_handler)
signal.signal(signal.SIGINT, signal_handler)

def check_java() -> bool:
    """Check if Java 25 is available."""
    try:
        result = subprocess.run(["java", "-version"], capture_output=True, text=True)
        output = result.stderr.lower() + result.stdout.lower()
        if "version" in output and "25" in output:
            log_info("Java 25 detected")
            return True
        else:
            log_error("Java 25 not found. Please ensure Dockerfile installs Java 25.")
            return False
    except FileNotFoundError:
        log_error("Java not found in PATH")
        return False

def download_paper() -> bool:
    """Download Paper from official API."""
    url = f"https://api.papermc.io/v2/projects/paper/versions/{MINECRAFT_VERSION}/builds/{PAPER_BUILD}/downloads/{JAR_NAME}"
    jar_path = Path(SERVER_DIR) / JAR_NAME
    
    log_info(f"Downloading Paper version {MINECRAFT_VERSION} build {PAPER_BUILD}...")
    
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Minecraft-Railway-Deploy"})
        with urllib.request.urlopen(req, timeout=60) as response:
            with open(jar_path, "wb") as f:
                shutil.copyfileobj(response, f)
        log_info(f"Paper downloaded successfully to {jar_path}")
        return True
    except urllib.error.HTTPError as e:
        log_error(f"Failed to download Paper: HTTP {e.code} - {e.reason}")
        return False
    except urllib.error.URLError as e:
        log_error(f"Failed to download Paper: {e.reason}")
        return False
    except Exception as e:
        log_error(f"Unexpected error downloading Paper: {e}")
        return False

def configure_server_properties() -> bool:
    """Configure server.properties file."""
    props_path = Path(SERVER_DIR) / "server.properties"
    
    # Read existing properties if any
    existing_props = {}
    if props_path.exists():
        with open(props_path, "r") as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    key, val = line.split("=", 1)
                    existing_props[key.strip()] = val.strip()
    
    # Default properties
    props = {
        "server-port": PORT,
        "online-mode": "false" if OFFLINE_MODE else "true",
        "enforce-secure-profile": "false" if OFFLINE_MODE else "true",
        "max-players": "10",
        "view-distance": "6",
        "simulation-distance": "4",
        "level-name": "world",
        "server-ip": "0.0.0.0",
        "allow-nether": "true",
        "allow-flight": "false",
        "spawn-animals": "true",
        "spawn-npcs": "true",
        "spawn-monsters": "true",
        "pvp": "true",
        "gamemode": "survival",
        "difficulty": "easy",
        "max-world-size": "29999984",
        "network-compression-threshold": "256",
        "rate-limit": "10",
        "enable-query": "false",
        "enable-rcon": "false",
        "enable-jmx-monitoring": "false",
    }
    
    # Update with existing properties (preserve custom settings)
    props.update(existing_props)
    
    # Write properties
    with open(props_path, "w") as f:
        f.write("# Minecraft server properties\n")
        f.write(f"# Generated by Railway deployment script\n")
        f.write(f"# {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        for key, val in props.items():
            f.write(f"{key}={val}\n")
    
    log_info("server.properties configured")
    return True

def create_eula() -> bool:
    """Create EULA file."""
    eula_path = Path(SERVER_DIR) / "eula.txt"
    
    if not eula_path.exists():
        with open(eula_path, "w") as f:
            f.write("# Minecraft EULA\n")
            f.write("# https://www.minecraft.net/en-us/eula\n")
            f.write("eula=true\n")
        log_warning("EULA file created with eula=true")
    else:
        # Check if eula is already true
        with open(eula_path, "r") as f:
            content = f.read()
            if "eula=true" not in content.lower():
                log_warning("EULA file exists but eula=true not found, updating...")
                with open(eula_path, "w") as f2:
                    f2.write("eula=true\n")
    
    return True

def get_connection_info() -> Tuple[Optional[str], Optional[str]]:
    """Get Railway TCP proxy connection info."""
    domain = os.environ.get("RAILWAY_TCP_PROXY_DOMAIN")
    port = os.environ.get("RAILWAY_TCP_PROXY_PORT")
    
    if domain and port:
        return domain, port
    else:
        log_warning("Railway TCP Proxy environment variables not found")
        log_warning("Please ensure a TCP Proxy is configured in Railway")
        log_warning("The Minecraft address will NOT be the HTTP domain")
        return None, None

def start_paper() -> bool:
    """Start Paper server."""
    global server_process
    
    jar_path = Path(SERVER_DIR) / JAR_NAME
    if not jar_path.exists():
        log_error(f"Paper JAR not found at {jar_path}")
        return False
    
    # Java arguments for low resource usage
    java_args = [
        "java",
        "-Xms512M",
        "-Xmx1536M",
        "-XX:+UseG1GC",
        "-Dcom.mojang.eula.agree=true",
        "-jar",
        str(jar_path),
        "nogui"
    ]
    
    log_info("Starting Paper server...")
    log_info(f"Server directory: {SERVER_DIR}")
    
    try:
        # Set working directory
        os.chdir(SERVER_DIR)
        
        # Start process
        server_process = subprocess.Popen(
            java_args,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            universal_newlines=True,
            bufsize=1
        )
        
        # Print online status
        time.sleep(5)  # Give server time to start
        if server_process.poll() is None:
            log_info("Minecraft server is online!")
            log_info(f"Internal port: {PORT}")
            
            # Get and print connection info
            domain, port = get_connection_info()
            if domain and port:
                log_info(f"Minecraft address: {domain}:{port}")
                log_info("Connect using this address in Minecraft Java Edition")
            else:
                log_warning("Unable to determine public Minecraft address")
                log_warning("Please configure a Railway TCP Proxy")
            
            if OFFLINE_MODE:
                log_warning("OFFLINE MODE ENABLED - Mojang/Microsoft authentication disabled")
                log_warning("This is less secure - only use for trusted networks or testing")
                log_warning("Clients must set 'online-mode=false' in their launcher")
                log_warning("TLauncher and similar clients must be configured for offline mode")
        
        # Forward logs
        for line in server_process.stdout:
            log_paper(line.strip())
            if server_process.poll() is not None:
                break
            
    except FileNotFoundError:
        log_error("Java command not found")
        return False
    except Exception as e:
        log_error(f"Failed to start Paper: {e}")
        return False
    
    return True

def main():
    """Main entry point."""
    log_info("Minecraft Paper Server Launcher")
    log_info(f"Version: {MINECRAFT_VERSION} Build: {PAPER_BUILD}")
    
    # Create server directory
    Path(SERVER_DIR).mkdir(parents=True, exist_ok=True)
    log_info(f"Server directory: {SERVER_DIR}")
    
    # Check Java
    if not check_java():
        sys.exit(1)
    
    # Check for Paper
    jar_path = Path(SERVER_DIR) / JAR_NAME
    if not jar_path.exists():
        if not download_paper():
            sys.exit(1)
    else:
        log_info("Paper JAR already exists")
    
    # Configure server
    if not configure_server_properties():
        sys.exit(1)
    if not create_eula():
        sys.exit(1)
    
    # Start server
    if not start_paper():
        sys.exit(1)
    
    # Wait for server to finish
    if server_process:
        try:
            server_process.wait()
        except KeyboardInterrupt:
            log_info("Received keyboard interrupt, shutting down...")
            server_process.terminate()
    
    log_info("Minecraft server stopped")

if __name__ == "__main__":
    main()
